### ISSUE TITLE
Render all vignette formats

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1051]
I'm not sure if this belongs in knitr or not, but it would be useful to have the ability to render multiple formats when building a vignette. (i.e. the equivalent of `output_format = "all"`)

**Comment by rmflight** [comment]
wouldn't that go in `rmarkdown`, where the `render` function lives?

**Comment by yihui** [comment]
I think it is possible to add a vignette engine to achieve that. The only problem is which format should be used for the R package, e.g. when both HTML and PDF vignettes exist (and I'm not sure if R CMD check will complain). I'll see what I can do.

**Comment by humburg** [comment]
I had a brief look at this and it seems to me that a vignette engine along the lines of `knitr::rmarkdown` that calls `render` with `output_format = "all"` *should* produce all the output formats specified in the file. However, when I try that with a vignette that has the following metadata block I end up with only the pdf version of the vignette in *doc/*.

```yaml
---
title: "Vignettes with multiple output formats"
author: "Peter Humburg"
output:
  html_document:
    standalone: true
    highlight: tango
    self-contained: true
    theme: cerulean
  pdf_document:
    highlight: tango
  
vignette: >
  %\VignetteIndexEntry{Multi-format vignettes}
  %\VignetteEngine{knitr::multiformat}
  \usepackage[utf8]{inputenc}
---
```

Not sure whether that means R simply defaults to the pdf if in doubt or that I'm doing something wrong. This is my first foray into vignette engines so I may well be missing something obvious. On the bright side `R CMD check` doesn't seem to mind.
