### ISSUE TITLE
encoding issue in metadata

### ISSUE THREAD

**Issue by stla** [yihui/knitr#1400]
Hello, 

 I don't know whether this is an issue with `knitr`, `rmarkdown` or RStudio.
I have metadata like this:
```
---
title: "Dyadic expansion with R"
author: "Stéphane Laurent"
date: '`r Sys.Date()`'
output:
  md_document:
    toc: yes
    variant: markdown
  html_document:
    keep_md: yes
---
```
When I click on *"Knit to html"* in RStudio, the two fields `md_document` and `html_document` are automatically exchanged. But then my first name becomes **StÃ©phane**.
