### ISSUE TITLE
CSS3 : Shining Gradient Text Effect with Shining Gradient Effect Background

### ISSUE THREAD

**Issue by englianhu** [yihui/knitr#1994]
I tried to refer to below references to set the styling chunk : 
- make my current gradient background shining
- make my current text gradient and shining

but there has problem which are:
- `class.output = 'bg-primary'` only support either gradient text or gradient background color
- how to make the text and backgound shining

Reference:
- [Style `knitr` Code Output Appearance in HTML with Custom CSS Classes](https://www.garrickadenbuie.com/blog/knitr-custom-class-output/)
- [**Tableau** 100 Color Palettes](https://public.tableau.com/en-us/gallery/100-color-palettes)
- [Shining Text Effect CSS3](https://codepen.io/fazlurr/pen/qbWMRv)

```css
/* https://bookdown.org/yihui/rmarkdown-cookbook/chunk-styling.html */
.bg-primary {
  color: #FFD64D;
  background: linear-gradient(to bottom, #375E97 0%, #4897D8 100%);
}

.shine {
    background: #FFD64D -webkit-gradient(linear, left top, right top, from(#222), to(#222), color-stop(0.5, yellow)) 0 0 no-repeat;
    -webkit-background-size: 150px;
    color: $text-color;
    -webkit-background-clip: text;
    -webkit-animation-name: shine;
    -webkit-animation-duration: $duration;
    -webkit-animation-iteration-count: infinite;
    text-shadow: 0 0px 0px golden-rod;
}
```
```r
knitr::opts_chunk$set(class.source = 'bg-success', class.output = 'bg-primary')
```
![Screenshot_20210510_213618](https://user-images.githubusercontent.com/7227582/117660251-eac81c00-b1d7-11eb-8f2d-d4ac88ce33b9.png)
**Above image shows gradient backgound color with static text color (both without shining).**

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by englianhu** [comment]
```css
/* https://stackoverflow.com/a/66029010/3806250 */
h1 { color: #002C54; }
h2 { color: #2F496E; }
h3 { color: #375E97; }

/* https://bookdown.org/yihui/rmarkdown-cookbook/chunk-styling.html */
.gradient {
  color: #FFD64D;
  background: linear-gradient(to bottom, #002C54 0%, #4CB5F5 100%);
  /*background-image: linear-gradient(to right,golden,golden, yellow, yellow);*/
  /*-webkit-background-clip: text;*/
  /*display: inline-block;*/
  /*padding: 14px;*/
  /*-webkit-text-fill-color: transparent;*/
  /*font-family: 'Stay Out Regular';*/
}

.shine {
	background: #FFD64D -webkit-gradient(linear, left top, right top, from(#222), to(#222), color-stop(0.5, yellow)) 0 0 no-repeat;
	-webkit-background-size: 150px;
	color: $text-color;
	-webkit-background-clip: text;
	-webkit-animation-name: shine;
	-webkit-animation-duration: $duration;
	-webkit-animation-iteration-count: infinite;
	text-shadow: 0 0px 0px golden-rod;
}
```
```r
knitr::opts_chunk$set(class.source = 'bg-success', class.output = 'gradient')
```
By refer to below links (**Reference**), is there any simple method to fit multi-functions `.gradient` and `.shine` into a class?
```r
knitr::opts_chunk$set(class.source = 'bg-success', class.output = c('shine', 'gradient'))
```
I tried to fit two classes `class.output = c('shine', 'gradient'))` as above but the output only shows `shine` despite the ordering of vector element.

---

**Reference** :
- [Add a CSS class to single code chunks in RMarkdown](https://stackoverflow.com/a/38168021/3806250)
- [Customizable functions to run before / after a code chunk, tweak the output, and manipulate chunk options](https://yihui.org/knitr/hooks/#output_hooks)
